services:
  hydrusclient:
    image: ghcr.io/hydrusnetwork/hydrus:latest
    container_name: hydrusclient
    restart: unless-stopped
    volumes:
      - ./data/hydrus-client:/opt/hydrus/db
      - ./data/hydrus-client-files:/opt/hydrus/db/client_files
      - ./data/hydrus-import-folder:/import

    tmpfs:
      - /tmp

  hydrusserver:
    image: ghcr.io/hydrusnetwork/hydrus:server
    container_name: hydrusserver
    restart: unless-stopped
    volumes:
      - ./data/hydrus-server:/opt/hydrus/db
      - ./data/hydrus-import-folder:/import

  hydrus-web:
    image: ghcr.io/floogulinc/hydrus-web:1.3.0
    container_name: hydrus-web
    restart: always

  proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 20d & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/.htpasswd:/.htpasswd
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
